from collections import Counter
from typing import Any

from src.models.linux_process_execution import LinuxProcessExecution
from src.models.threat_finding import ThreatFinding


def generate_linux_execution_statistics(
    linux_executions: list[LinuxProcessExecution],
    advanced_linux_findings: list[ThreatFinding],
) -> dict[str, Any]:
    """
    Generate statistics for the Advanced Linux Execution Analysis Layer.

    Args:
        linux_executions:
            Normalized Linux process execution objects analyzed by the
            advanced Linux detectors.

        advanced_linux_findings:
            Threat findings generated by the advanced Linux detectors.

    Returns:
        Dictionary containing execution, user, executable, and MITRE
        statistics.
    """

    executable_counter = Counter(execution.executable
        for execution in linux_executions if execution.executable)

    user_counter = Counter(execution.user
        for execution in linux_executions if execution.user)

    mitre_counter = Counter(finding.technique
        for finding in advanced_linux_findings
        if getattr(finding, "technique", ""))

    unique_executables = set(executable_counter)

    return {
        "total_executions": len(linux_executions),
        "suspicious_executions": len(advanced_linux_findings),
        "unique_executables": len(unique_executables),
        "top_executables": executable_counter.most_common(10),
        "top_users": user_counter.most_common(10),
        "mitre_statistics": mitre_counter.most_common(),
    }